# -*- coding: utf-8 -*-
"""majorProjectPorotype2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPJMzjsmx0UtR8olKXflY52-ucNt0n4z
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
import numpy as np
import gradio as gr
import cv2
from typing import Tuple, Optional, Dict

# ============================================================================
# MODEL DEFINITIONS
# ============================================================================

class ImprovedResNet(nn.Module):
    """Binary classification model (Real vs Fake)"""
    def __init__(self, num_classes=2, dropout_rate=0.5):
        super(ImprovedResNet, self).__init__()

        # Rectified: Replaced deprecated 'pretrained=False' with 'weights=None'
        self.resnet = models.resnet18(weights=None)

        # Freeze all parameters except the last 10
        for param in list(self.resnet.parameters())[:-10]:
            param.requires_grad = False

        num_features = self.resnet.fc.in_features
        self.resnet.fc = nn.Sequential(
            nn.Dropout(dropout_rate),
            nn.Linear(num_features, 256),
            nn.ReLU(),
            nn.Dropout(dropout_rate/2),
            nn.Linear(256, num_classes)
        )

        # Initialize weights for the new fully connected layer
        for m in self.resnet.fc.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        return self.resnet(x)


class DualEfficientNetB0(nn.Module):
    """Attribution model - Dual-branch architecture: RGB + FFT frequency domain"""
    def __init__(self, num_classes=3, pretrained=False, dropout=0.3):
        super().__init__()

        # Rectified: Replaced deprecated 'pretrained=...' with modern 'weights=...' API
        rgb_weights = models.EfficientNet_B0_Weights.DEFAULT if pretrained else None
        rgb_model = models.efficientnet_b0(weights=rgb_weights)

        self.rgb_backbone = nn.Sequential(
            rgb_model.features,
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten()
        )

        # Rectified: Replaced deprecated 'pretrained=...' with modern 'weights=...' API
        fft_weights = models.EfficientNet_B0_Weights.DEFAULT if pretrained else None
        fft_model = models.efficientnet_b0(weights=fft_weights)

        self.fft_backbone = nn.Sequential(
            fft_model.features,
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten()
        )

        feat_dim = 1280  # EfficientNet-B0 feature dimension
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(feat_dim * 2, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(512, num_classes)
        )

    def forward(self, rgb, fft):
        rgb_feat = self.rgb_backbone(rgb)
        fft_feat = self.fft_backbone(fft)
        combined = torch.cat([rgb_feat, fft_feat], dim=1)
        out = self.classifier(combined)
        return out


# ============================================================================
# GRAD-CAM IMPLEMENTATION
# ============================================================================

class GradCAM:
    """Gradient-weighted Class Activation Mapping for model interpretability"""
    def __init__(self, model, target_layer, is_dual_input=False):
        self.model = model
        self.target_layer = target_layer
        self.is_dual_input = is_dual_input
        self.gradients = None
        self.activations = None
        self.hook_layers()

    def hook_layers(self):
        def forward_hook(module, input, output):
            self.activations = output.detach()

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0].detach()

        self.target_layer.register_forward_hook(forward_hook)
        self.target_layer.register_full_backward_hook(backward_hook)

    def generate_cam(self, input_tensor, target_class=None, fft_tensor=None):
        self.model.eval()

        # Handle dual-input models (attribution model needs both RGB and FFT)
        if self.is_dual_input and fft_tensor is not None:
            output = self.model(input_tensor, fft_tensor)
        else:
            output = self.model(input_tensor)

        if target_class is None:
            target_class = output.argmax(dim=1).item()

        self.model.zero_grad()
        output[0, target_class].backward()

        # Check if gradients were captured
        if self.gradients is None:
            raise RuntimeError("Gradients were not captured. Check hook logic or target layer.")

        # Pool gradients across channels
        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        # Weight the feature maps
        cam = (weights * self.activations).sum(dim=1, keepdim=True)
        # Apply ReLU
        cam = F.relu(cam)
        # Resize to original image size
        cam = F.interpolate(cam, size=input_tensor.shape[2:], mode='bilinear', align_corners=False)
        cam = cam.squeeze().cpu().numpy()

        # Normalize the CAM
        cam_min = cam.min()
        cam_max = cam.max()
        cam = (cam - cam_min) / (cam_max - cam_min + 1e-8)

        return cam, target_class


# ============================================================================
# PREPROCESSING UTILITIES
# ============================================================================

def get_fft_spectrum(image_tensor: torch.Tensor) -> torch.Tensor:
    """Convert image to FFT frequency domain representation"""
    # Squeeze batch dimension and convert to numpy
    img_np = image_tensor.squeeze(0).cpu().numpy()

    # Transpose from (C, H, W) to (H, W, C)
    if img_np.shape[0] == 3:
        img_np = np.transpose(img_np, (1, 2, 0))

    # Denormalize (assuming standard ImageNet stats)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img_np = (img_np * std + mean) * 255.0
    img_np = np.clip(img_np, 0, 255).astype(np.uint8)

    # Convert to grayscale
    gray = cv2.cvtColor(img_np, cv2.COLOR_RGB2GRAY)

    # Perform FFT
    fft = np.fft.fft2(gray)
    fft_shift = np.fft.fftshift(fft)
    magnitude = np.log(np.abs(fft_shift) + 1)

    # Normalize magnitude map to [0, 1]
    mag_min = magnitude.min()
    mag_max = magnitude.max()
    magnitude = (magnitude - mag_min) / (mag_max - mag_min + 1e-8)

    # Stack to 3 channels to match model input
    fft_rgb = np.stack([magnitude] * 3, axis=0)

    tensor = torch.from_numpy(fft_rgb).float()

    # --- RECTIFIED: Added normalization ---
    # The EfficientNet backbone expects inputs normalized with ImageNet stats.
    # The FFT image should be normalized just like the RGB image.
    normalize = transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    return normalize(tensor)
    # --- End of fix ---


def preprocess_image(image: Image.Image, size: int = 224) -> torch.Tensor:
    """Standard preprocessing for RGB images"""
    transform = transforms.Compose([
        transforms.Resize((size, size)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    return transform(image).unsqueeze(0)


def overlay_heatmap(image: np.ndarray, heatmap: np.ndarray, alpha: float = 0.5) -> np.ndarray:
    """Overlay Grad-CAM heatmap on original image"""
    heatmap_colored = cv2.applyColorMap((heatmap * 255).astype(np.uint8), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

    # Ensure image is in 0-255 range, uint8
    if image.max() <= 1.0:
        image = (image * 255).astype(np.uint8)
    if image.dtype != np.uint8:
         image = image.astype(np.uint8)

    overlay = cv2.addWeighted(image, 1 - alpha, heatmap_colored, alpha, 0)
    return overlay


# ============================================================================
# DEFAKE PIPELINE
# ============================================================================

class DeFakePipeline:
    """Main pipeline for deepfake detection and attribution"""

    def __init__(self, binary_model_path: str, attribution_model_path: str, device: str = 'cuda'):
        self.device = torch.device(device if torch.cuda.is_available() else 'cpu')
        print(f"Using device: {self.device}")

        try:
            # Load binary model
            self.binary_model = ImprovedResNet(num_classes=2, dropout_rate=0.5)
            self.binary_model.load_state_dict(torch.load(binary_model_path, map_location=self.device))
            self.binary_model.to(self.device)
            self.binary_model.eval()
            print("Binary model loaded successfully.")

            # Load attribution model
            self.attribution_model = DualEfficientNetB0(num_classes=3, pretrained=False, dropout=0.3)
            # Load only the model_state_dict from the checkpoint
            attribution_state = torch.load(attribution_model_path, map_location=self.device)

            # Check if the loaded object is a dictionary and has 'model_state_dict'
            if isinstance(attribution_state, dict) and 'model_state_dict' in attribution_state:
                self.attribution_model.load_state_dict(attribution_state['model_state_dict'])
                print("Attribution model checkpoint loaded successfully.")
            else:
                # Assume it's just the state_dict
                self.attribution_model.load_state_dict(attribution_state)
                print("Attribution model state_dict loaded successfully.")

            self.attribution_model.to(self.device)
            self.attribution_model.eval()

        except FileNotFoundError as e:
            print(f"FATAL ERROR: Model file not found. {e}")
            raise
        except Exception as e:
            print(f"FATAL ERROR: Error loading models. {e}")
            raise

        # Initialize Grad-CAM
        self.binary_gradcam = GradCAM(self.binary_model, self.binary_model.resnet.layer4[-1], is_dual_input=False)
        # Target the last conv block of the EfficientNet features
        self.attribution_gradcam = GradCAM(self.attribution_model, self.attribution_model.rgb_backbone[0][-1], is_dual_input=True)

        # CHANGED: Reversed label order - Fake is now index 0, Real is index 1
        self.binary_classes = ['Fake', 'Real']
        self.gan_classes = ['StyleGAN1', 'StyleGAN2', 'StyleGAN3']
        print("DeFakePipeline initialized.")

    def predict(self, image: Image.Image) -> Dict:
        """Run complete detection pipeline with conditional attribution"""
        if image is None:
            return {
                'error': 'No image provided',
                'binary_result': None,
                'attribution_result': None
            }

        # Prepare image
        img_array = np.array(image.resize((224, 224)))
        img_tensor = preprocess_image(image).to(self.device)

        # ========================================================================
        # STAGE 1: BINARY CLASSIFICATION (Real vs Fake)
        # ========================================================================
        with torch.no_grad():
            binary_output = self.binary_model(img_tensor)
            binary_probs = F.softmax(binary_output, dim=1)[0]
            binary_pred = binary_probs.argmax().item()
            binary_conf = binary_probs[binary_pred].item()

        # --- RECTIFIED: Added error handling for Grad-CAM ---
        try:
            # Generate Grad-CAM for binary model (requires gradients)
            img_tensor_grad = img_tensor.clone().requires_grad_(True)
            binary_cam, _ = self.binary_gradcam.generate_cam(img_tensor_grad, target_class=binary_pred)
            binary_overlay = overlay_heatmap(img_array, binary_cam, alpha=0.4)
        except Exception as e:
            print(f"Error generating binary Grad-CAM: {e}")
            binary_overlay = img_array # Show original image on failure
        # --- End of fix ---

        result = {
            'binary_prediction': self.binary_classes[binary_pred],
            'binary_confidence': f"{binary_conf * 100:.2f}%",
            'binary_probs': {
                'Fake': f"{binary_probs[0].item() * 100:.2f}%",
                'Real': f"{binary_probs[1].item() * 100:.2f}%"
            },
            'binary_heatmap': binary_overlay,
            # CHANGED: Now checking if index 0 (Fake) instead of index 1
            'is_fake': binary_pred == 0
        }

        # ========================================================================
        # STAGE 2: ATTRIBUTION (Only executed if image is classified as FAKE)
        # ========================================================================
        # CHANGED: Now checking if index 0 (Fake) instead of index 1
        if binary_pred == 0:  # FAKE detected
            # Prepare FFT frequency domain representation
            fft_tensor = get_fft_spectrum(img_tensor).unsqueeze(0).to(self.device)

            # Run attribution model
            with torch.no_grad():
                attribution_output = self.attribution_model(img_tensor, fft_tensor)
                attribution_probs = F.softmax(attribution_output, dim=1)[0]
                gan_pred = attribution_probs.argmax().item()
                gan_conf = attribution_probs[gan_pred].item()

            # --- RECTIFIED: Added error handling for Grad-CAM ---
            try:
                # Generate Grad-CAM for attribution model (requires gradients)
                img_tensor_grad = img_tensor.clone().requires_grad_(True)
                fft_tensor_grad = fft_tensor.clone().requires_grad_(True)
                attr_cam, _ = self.attribution_gradcam.generate_cam(
                    img_tensor_grad,
                    target_class=gan_pred,
                    fft_tensor=fft_tensor_grad
                )
                attr_overlay = overlay_heatmap(img_array, attr_cam, alpha=0.4)
            except Exception as e:
                print(f"Error generating attribution Grad-CAM: {e}")
                attr_overlay = img_array # Show original image on failure
            # --- End of fix ---

            result['gan_type'] = self.gan_classes[gan_pred]
            result['gan_confidence'] = f"{gan_conf * 100:.2f}%"
            result['gan_probs'] = {
                'StyleGAN1': f"{attribution_probs[0].item() * 100:.2f}%",
                'StyleGAN2': f"{attribution_probs[1].item() * 100:.2f}%",
                'StyleGAN3': f"{attribution_probs[2].item() * 100:.2f}%"
            }
            result['attribution_heatmap'] = attr_overlay
            result['attribution_performed'] = True
        else:  # REAL detected - skip attribution
            result['gan_type'] = None
            result['gan_confidence'] = None
            result['gan_probs'] = None
            result['attribution_heatmap'] = None
            result['attribution_performed'] = False

        return result


# ============================================================================
# GRADIO INTERFACE
# ============================================================================

def create_gradio_interface(binary_model_path: str, attribution_model_path: str):
    """Create and launch Gradio interface"""

    # Initialize the pipeline
    try:
        pipeline = DeFakePipeline(binary_model_path, attribution_model_path)
    except Exception as e:
        print(f"Failed to initialize pipeline: {e}")
        # Create a dummy interface to show the error
        with gr.Blocks() as demo:
            gr.Markdown(f"# <h1>🔥 Error</h1>\n## Failed to load models.\nCheck console for details.\n`{e}`")
        return demo

    def process_image(image):
        if image is None:
            return None, "⚠️ Please upload an image", None, None, None

        # Convert image to RGB if it has an alpha channel
        if image.mode == 'RGBA':
            image = image.convert('RGB')

        try:
            result = pipeline.predict(image)
        except Exception as e:
            print(f"Error during prediction: {e}")
            return None, f"⚠️ An error occurred during analysis: {e}", None, None, None

        # Format Binary Detection Result
        binary_text = f"""
        ### 🔍 Binary Detection Result

        **Prediction:** <span style="font-size: 24px; font-weight: bold; color: {'#ef4444' if result['is_fake'] else '#10b981'};">{result['binary_prediction']}</span>

        **Confidence:** {result['binary_confidence']}

        **Probability Distribution:**
        - 🔴 Fake: {result['binary_probs']['Fake']}
        - 🟢 Real: {result['binary_probs']['Real']}

        ---

        **Grad-CAM Explanation:** The heatmap shows regions that influenced the binary classification.
        Red/yellow areas had the strongest impact on the decision.
        """

        # Format Attribution Result (only if fake)
        if result['attribution_performed']:
            attribution_text = f"""
            ### 🎭 GAN Attribution Analysis

            **Detected GAN Type:** <span style="font-size: 20px; font-weight: bold; color: #8b5cf6;">{result['gan_type']}</span>

            **Confidence:** {result['gan_confidence']}

            **Probability Distribution:**
            - 🟣 StyleGAN1: {result['gan_probs']['StyleGAN1']}
            - 🔵 StyleGAN2: {result['gan_probs']['StyleGAN2']}
            - 🟢 StyleGAN3: {result['gan_probs']['StyleGAN3']}

            ---

            **Grad-CAM Explanation:** The heatmap highlights frequency-domain artifacts
            characteristic of {result['gan_type']}. Red/yellow regions show the most
            discriminative features for this GAN architecture.
            """
            attribution_img = result['attribution_heatmap']
        else:
            attribution_text = f"""
            ### ✅ Attribution Skipped

            **Reason:** Image classified as **Real**

            Attribution analysis is only performed on images detected as fake.
            Since this image passed the binary authenticity check, no GAN
            attribution is necessary.
            """
            attribution_img = None

        # Explanation footer
        explanation = """
        ### 📊 Understanding Grad-CAM Visualizations

        **Grad-CAM (Gradient-weighted Class Activation Mapping)** highlights which regions
        of the image were most important for the model's decision:

        - 🔴 **Red/Hot colors**: High importance - these regions strongly influenced the prediction
        - 🟡 **Yellow/Warm colors**: Moderate importance
        - 🔵 **Blue/Cool colors**: Low importance - minimal impact on the decision

        **For Binary Detection:** Looks for overall authenticity markers (artifacts, inconsistencies)

        **For Attribution:** Analyzes frequency-domain patterns specific to each GAN architecture
        """

        return (
            result['binary_heatmap'],
            binary_text,
            attribution_img,
            attribution_text,
            explanation
        )

    # Custom CSS for better styling
    css = """
    .gradio-container {
        font-family: 'Arial', sans-serif;
        max-width: 1400px !important;
    }
    .output-image {
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    .markdown-text {
        font-size: 16px;
        line-height: 1.6;
    }
    #title {
        text-align: center;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
    }
    """

    with gr.Blocks(css=css, theme=gr.themes.Soft()) as demo:
        gr.Markdown(
            """
            <div id="title">
                <h1>🛡️ DeFake Detection System</h1>
                <p>Advanced deepfake detection with GAN attribution and explainable AI</p>
            </div>
            """,
            elem_id="title"
        )

        with gr.Row():
            with gr.Column(scale=1):
                input_image = gr.Image(
                    label="📤 Upload Image",
                    type="pil",
                    height=400
                )
                predict_btn = gr.Button(
                    "🔍 Analyze Image",
                    variant="primary",
                    size="lg"
                )

                gr.Markdown(
                    """
                    ### 📋 How it works:
                    1. **Binary Detection**: Classifies image as Real or Fake
                    2. **GAN Attribution**: If fake, identifies the GAN type (StyleGAN1/2/3)
                    3. **Explainability**: Grad-CAM highlights influential regions

                    **Supported formats**: JPG, PNG, JPEG
                    """
                )

            with gr.Column(scale=2):
                with gr.Row():
                    binary_heatmap = gr.Image(
                        label="🔴 Binary Detection (Grad-CAM)",
                        type="numpy",
                        height=350
                    )
                    attribution_heatmap = gr.Image(
                        label="🎨 Attribution (Grad-CAM)",
                        type="numpy",
                        height=350
                    )

                with gr.Row():
                    with gr.Column():
                        binary_result = gr.Markdown(label="Binary Result")
                    with gr.Column():
                        attribution_result = gr.Markdown(label="Attribution Result")

                explanation = gr.Markdown()

        predict_btn.click(
            fn=process_image,
            inputs=[input_image],
            outputs=[binary_heatmap, binary_result, attribution_heatmap, attribution_result, explanation]
        )

        gr.Markdown(
            """
            ---
            ### 🔬 Technical Details
            - **Binary Model**: ResNet18 with improved architecture
            - **Attribution Model**: Dual EfficientNet-B0 (RGB + FFT branches)
            - **XAI Method**: Grad-CAM for visual explanations
            """
        )

    return demo


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == "__main__":
    # Update these paths to your model files
    BINARY_MODEL_PATH = "/content/drive/MyDrive/23 resent18 model.pth"
    ATTRIBUTION_MODEL_PATH = "/content/drive/MyDrive/best_model gan atribution.pth"

    demo = create_gradio_interface(BINARY_MODEL_PATH, ATTRIBUTION_MODEL_PATH)
    demo.launch(
        server_name="0.0.0.0",
        share=True, # Set to True if running in Colab to get a public link
        show_error=True,
        debug=True # Add debug=True to see more errors
    )

